const INTERNAL_SERVER_ERROR = 500;
const BAD_REQUEST = 400;
const UN_AUTHORIZED = 401;
const NOT_FOUND = 404;
const FORBIDDEN = 403;

module.exports = {
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  UN_AUTHORIZED,
  NOT_FOUND,
  FORBIDDEN,
};
